// <auto-generated />
using System;
using KPI5.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KPI5.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KPI5.Domain.Entities.KPI5.Kpi5Entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Circle")
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Circle");

                    b.Property<string>("Kpi")
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Kpi");

                    b.Property<int?>("PeriodMonth")
                        .HasMaxLength(2)
                        .HasColumnType("INT")
                        .HasColumnName("PeriodMonth");

                    b.Property<int?>("PeriodYear")
                        .HasMaxLength(4)
                        .HasColumnType("INT")
                        .HasColumnName("PeriodYear");

                    b.Property<string>("Periodicity")
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Periodicity");

                    b.Property<string>("Range")
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR")
                        .HasColumnName("Range");

                    b.Property<float?>("Value")
                        .HasColumnType("DECIMAL")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("KpisDB", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
