name: Flask Web App to Azure

env:
  AZURE_WEBAPP_NAME: kpi5Graphics
  RESOURCE_GROUP: Womenplusplus
  PYTHON_VERSION: '3.10.x'
  APP_LOCATION: "src/FlaskGraphics/"

on:
  push:
    branches: [ "main" ]
    paths: ${{ env.PYTHON_VERSION }}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Create and start virtual environment
      run: |
          python -m venv venv
          source venv/bin/activate

    - name: Install dependencies
      run: pip install -r ${{ env.PYTHON_VERSION }}/requirements.txt

    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: |
          .
          !venv/

    - name: Log in to Azure CLI using service principal
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS_GRAPHS }}


    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_GRAPHS }}
