name: WebAPI CI/CD to Azure

env:
  AZURE_WEBAPP_NAME: kpi5
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: 7.0

on:
  push:
    branches: [ "src/WebApi/" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore
        
      - name: Build
        run: dotnet build -c Release
        
      - name: Publish
        run: dotnet publish -c Release -o '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/kpi5'
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/kpi5'
