name: WebAPI CI/CD to Azure

env:
  AZURE_WEBAPP_NAME: kpi5
  AZURE_WEBAPP_PACKAGE_PATH: './publish'
  DOTNET_VERSION: 7.0
  PROJECT_PATH: 'src/WebApi'

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          
      - name: Restore
        run: dotnet restore
        working-directory: ${{ env.PROJECT_PATH }}
        
      - name: Build
        run: dotnet build
        working-directory: ${{ env.PROJECT_PATH }}
        
      - name: Publish
        run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        working-directory: ${{ env.PROJECT_PATH }}
        
      - name: Publish
        run: dotnet publish --configuration Release --output ${{ github.workspace }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/kpi5 API/API.csproj
        working-directory: ${{ env.PROJECT_PATH }}
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/kpi5
